# Generated by Django 4.1.5 on 2023-01-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album_cover_url',
            field=models.FileField(blank=True, upload_to='album_covers/'),
        ),
        migrations.AddField(
            model_name='song',
            name='audio_file_url',
            field=models.FileField(blank=True, upload_to='audio_files/'),
        ),
    ]
